In [4]:
import numpy as np
import torch

In [14]:
test = np.array([2,4,2,4,1,124,1,1,1])

In [15]:
np.bincount(test)

array([0, 4, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [16]:
torch.bincount(torch.tensor(test))

tensor([0, 4, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1])

In [68]:
test_dict = {0:2, 1:2, 3:4, 4:-1, 5:2}

test_states = np.array(list(test_dict.values()))
test_shift = test_states + np.ones(len(test_dict), dtype=np.uint8)
#test_shift
np.bincount(test_shift)

array([1, 0, 0, 3, 0, 1])

In [61]:
test_states

array(dict_values([2, 2, 4, -1, 2]), dtype=object)

In [18]:
test_dict.values()

dict_values([2, 2, 4, 1, 2])

In [19]:
shuf_test = np.random.shuffle(test)

In [20]:
test

array([  2,   4,   1,   4, 124,   1,   1,   2,   1])

In [24]:
test_nei = np.random.randint(len(test), size=(len(test), 4))

In [44]:
test_nei 

array([[0, 6, 7, 5],
       [5, 0, 8, 2],
       [0, 1, 5, 8],
       [0, 8, 0, 7],
       [8, 8, 4, 7],
       [5, 1, 6, 6],
       [4, 5, 7, 2],
       [5, 8, 5, 0],
       [1, 6, 1, 8]])

In [35]:
test_r = np.random.rand(len(test), 4)

In [37]:
for test_n, test_ni, test_rvec in zip(test, test_nei, test_r):
    print(f"n:{test_n}, ni:{test_ni}, r:{test_rvec}")

n:2, ni:[0 6 7 5], r:[0.85791013 0.4162825  0.5290101  0.30785212]
n:4, ni:[5 0 8 2], r:[0.78140761 0.44844075 0.1645715  0.92306815]
n:1, ni:[0 1 5 8], r:[0.90902217 0.37766672 0.34315819 0.66524254]
n:4, ni:[0 8 0 7], r:[0.65548506 0.48652216 0.65750446 0.44463445]
n:124, ni:[8 8 4 7], r:[0.92990162 0.11043028 0.20338859 0.93607972]
n:1, ni:[5 1 6 6], r:[0.74063055 0.40802467 0.33166891 0.21506032]
n:1, ni:[4 5 7 2], r:[0.02032626 0.68182334 0.51093818 0.2314154 ]
n:2, ni:[5 8 5 0], r:[0.66348392 0.27056879 0.19343116 0.86810014]
n:1, ni:[1 6 1 8], r:[0.75526142 0.14606446 0.12763841 0.95237588]


In [40]:
test_r > 0.4

array([[ True,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [41]:
(test_r > 0.4) * test_nei

array([[0, 6, 7, 0],
       [5, 0, 0, 2],
       [0, 0, 0, 8],
       [0, 8, 0, 7],
       [8, 0, 0, 7],
       [5, 1, 0, 0],
       [0, 5, 7, 0],
       [5, 0, 0, 0],
       [1, 0, 0, 8]])

In [45]:
np.sign(-1)

-1

In [50]:
np.ones(4, dtype=np.uint8)

array([1, 1, 1, 1], dtype=uint8)

In [51]:
test_nei - np.ones((len(test), 4), dtype=np.uint8)

array([[-1,  5,  6,  4],
       [ 4, -1,  7,  1],
       [-1,  0,  4,  7],
       [-1,  7, -1,  6],
       [ 7,  7,  3,  6],
       [ 4,  0,  5,  5],
       [ 3,  4,  6,  1],
       [ 4,  7,  4, -1],
       [ 0,  5,  0,  7]])

In [53]:
np.ones(test_nei.shape, dtype=np.uint8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [70]:
torch.cuda.is_available()

True

In [71]:
test_nei

array([[0, 6, 7, 5],
       [5, 0, 8, 2],
       [0, 1, 5, 8],
       [0, 8, 0, 7],
       [8, 8, 4, 7],
       [5, 1, 6, 6],
       [4, 5, 7, 2],
       [5, 8, 5, 0],
       [1, 6, 1, 8]])

In [72]:
torch.tensor(test_nei)

tensor([[0, 6, 7, 5],
        [5, 0, 8, 2],
        [0, 1, 5, 8],
        [0, 8, 0, 7],
        [8, 8, 4, 7],
        [5, 1, 6, 6],
        [4, 5, 7, 2],
        [5, 8, 5, 0],
        [1, 6, 1, 8]])

In [75]:
A = np.ones((3,3))

In [76]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.fill_diagonal(A, 34)

In [78]:
A

array([[34.,  1.,  1.],
       [ 1., 34.,  1.],
       [ 1.,  1., 34.]])

In [103]:
e = 0.1

adj = np.array([[0, 1, 1, 0],
                [1, 0, 1, 0],
                [1, 1, 0, 1],
                [0, 0, 1, 0]])

degrees = np.sum(adj, axis=1)

errors = e / degrees

Q = errors.reshape(-1,1) * adj

np.fill_diagonal(Q, 1-e)

In [104]:
Q

array([[0.9       , 0.05      , 0.05      , 0.        ],
       [0.05      , 0.9       , 0.05      , 0.        ],
       [0.03333333, 0.03333333, 0.9       , 0.03333333],
       [0.        , 0.        , 0.1       , 0.9       ]])

In [81]:
degrees

array([2, 2, 3, 1])

In [83]:
e / degrees

array([0.05      , 0.05      , 0.03333333, 0.1       ])

In [106]:
import networkx as nx

G = nx.barabasi_albert_graph(10, 2)
M = nx.adjacency_matrix(G).todense()

In [107]:
M

array([[0, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0]])

In [110]:
list(range(10))[1:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]